apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"  # Only works on local clusters like Docker Desktop
