services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
