version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
      - UPLOAD_FOLDER=/app/uploads