version: "3.8"

services:
  flask-app:
    image: rohan2304/flask-secrets-env:latest
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
    secrets:
      - api_key

secrets:
  api_key:
    file: ./secrets/api_key.txt
