version: '3.8'

services:
  web:
    build: ./app
    container_name: fastapi_app
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; print(requests.get('http://localhost:8000/health').status_code)"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      web:
        condition: service_healthy
