name: Test, Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'week-1/file-upload-app/**'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'week-1/file-upload-app/**'
      - '.github/workflows/docker.yml'
permissions:
      contents: read
      packages: write
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      working-directory: ./week-1/file-upload-app
      run: |
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./week-1/file-upload-app
      run: |
        pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./week-1/file-upload-app
        push: true
        tags: ghcr.io/sachelsout/file-upload-app:latest
